### ISSUE TITLE
Is there a mechanism to disable authentication ?

### ISSUE THREAD

**Issue by ncoutinho1** [DeemOpen/zkui#15]
We plan to deploy this in our QA environment and were looking for options to disable any authentication.

**Comment by arjunsurendra04** [comment]
With some code change yes. Take a look at AuthFilter.java
However the reason for having auth is to track the change history. If the reason for disabling is so that people dont know the username/pwd you can put the default one in the property: loginMessage which gets displayed on the login page so that people dont need to remember it.
